server:
  port: 8888
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bibased
      username: root
      password: fourteam
      init-SQL: "set names utf8mb4;"
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
